name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      extensions: mbstring, sqlite, pdo_sqlite, intl

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: '8.0'
          extensions: ${{ env.extensions }}
          key: php-extensions-cache

      - name: Cache extensions
        uses: actions/cache@v2
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: ${{ env.extensions }}
          coverage: pcov
          tools: composer:v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: dependencies-composer-${{ hashFiles('composer.json') }}
          restore-keys: dependencies-composer-

      - name: Get npm cache directory
        id: npmcache
        run: echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.npmcache.outputs.dir }}
          key: dependencies-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: dependencies-npm-

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Install npm dependencies
        run: npm ci --prefer-offline

      - name: Build frontend
        run: npm run production

      - name: Run tests
        run: composer test

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: deployphp/action@master
        with:
          private-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          dep: deploy stage=production
